name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Student evaluation.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore "Student evaluation"

    - name: Build
      run: dotnet build "Student evaluation" --configuration $BUILD_CONFIG

    - name: Test
      run: dotnet test "Student evaluation.Test/Student evaluation.Test.csproj" --configuration $BUILD_CONFIG
