name: .NET Workflow

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: 7.0.x
  CONFIGURATION: Release
  SOLUTION_DIRECTORY: Student evaluation
  TEST_DIRECTORY: Student evaluation.Test

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest  # Switch to a Windows runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore NuGet Packages
      run: dotnet restore "${{ env.SOLUTION_DIRECTORY }}"

    - name: Build Solution
      run: dotnet build "${{ env.SOLUTION_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}

    - name: Run Tests
      run: dotnet test "${{ env.TEST_DIRECTORY }}" --no-build --verbosity normal

    - name: Publish
      run: dotnet publish "${{ env.SOLUTION_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output ./output

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: publish-output
        path: ./output

