name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Student evaluation.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.x'
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1
    - name: Build
      run:  msbuild.exe .\Student evaluation.sln
    - name: Setup VSTest and add to PATH
      uses: darenm/Setup-VSTest@v1
    - name: Run VSTest
      id: run_vstest
      run: vstest.console.exe .\Student evaluation.Test\bin\Debug\Student evaluation.Test.dll /Platform:x64
